# Generated by Django 3.1.13 on 2021-11-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary", "0002_auto_20211102_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="beneficiary.province"
            ),
        ),
    ]
