# Generated by Django 3.1.13 on 2021-11-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_workdetail'),
        ('beneficiary', '0004_permission'),
    ]

    operations = [
    ]
