# Generated by Django 3.1.13 on 2021-11-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0005_merge_20211104_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
