# Generated by Django 3.1.13 on 2021-11-04 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0007_servicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('other_name', models.CharField(max_length=200, null=True, verbose_name='Other Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, verbose_name='Gender')),
                ('profile_photo', models.ImageField(upload_to='profile_photo/')),
                ('beneficiary_code', models.UUIDField(default=uuid.UUID('c30536a2-49fc-4cad-9096-64356a8803c6'), editable=False)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('seperated', 'Seperated'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=100, verbose_name='Marital Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['created'],
            },
        ),
    ]
