# Generated by Django 3.1.13 on 2021-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0007_servicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Second Name')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('agend_ID', models.CharField(default='AEAC965', max_length=100, verbose_name='Agent Id')),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender'), (4, 'Other')], default=4, max_length=50, verbose_name='Gender')),
                ('location', models.CharField(max_length=500, verbose_name='Assigned Location')),
            ],
        ),
    ]
