# Generated by Django 3.1.13 on 2021-11-05 07:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0009_auto_20211105_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_code',
            field=models.UUIDField(default=uuid.UUID('8ec69c2d-4076-4069-b16e-8e7136fc865d'), editable=False),
        ),
    ]
