# Generated by Django 3.1.13 on 2021-11-05 10:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0009_auto_20211105_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_code',
            field=models.UUIDField(default=uuid.UUID('73a3d6c2-6d31-4875-99bc-f07d71013801'), editable=False),
        ),
    ]
