# Generated by Django 3.1.13 on 2021-11-05 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0010_auto_20211105_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_first_name', models.CharField(max_length=200, verbose_name='Father First Name')),
                ('father_last_name', models.CharField(max_length=200, verbose_name='Father Last Name')),
                ('mother_first_name', models.CharField(max_length=200, verbose_name='Mother First Name')),
                ('mother_last_name', models.CharField(max_length=200, verbose_name='Mother Last Name')),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='junior_secondary_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='name_of_spouse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='number_of_siblings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='senior_secondary_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='tertiary_eduction_qualification',
            field=models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('doctrate', 'Doctrate'), ('phd', 'PHD')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_code',
            field=models.UUIDField(default=uuid.UUID('be5c13ff-8e39-40d6-bdb6-70389300ff87'), editable=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='parent_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='beneficiary.beneficiaryparent'),
            preserve_default=False,
        ),
    ]
