# Generated by Django 3.1.13 on 2021-11-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary", "0011_auto_20211124_1413"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hmis_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="HMIS Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Just enter name without 'Hostpial' or 'Clinic`, i.e for `Kitwe General Hospital` just enter `Kitwe General`.",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        default=1,
                        help_text="District in which the facility is located",
                        max_length=250,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beneficiary.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="FacilityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Facility Type Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImplementingPartner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "ip_type",
                    models.IntegerField(
                        choices=[
                            (1, "Non-Profit Organization"),
                            (2, "Company"),
                            (3, "Government"),
                            (4, "Other"),
                        ],
                        default=1,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is still an active Implementing Partner",
                        verbose_name="Is Active",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=200, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Last Name"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Department"
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("degree", "Degree"),
                            ("masters", "Masters"),
                            ("doctrate", "Doctrate"),
                            ("phd", "PHD"),
                        ],
                        default="Diploma",
                        max_length=100,
                        null=True,
                        verbose_name="Qualification",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beneficiary.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Provider",
                "verbose_name_plural": "Service Providers",
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type",
            field=models.ForeignKey(
                default=1,
                help_text="Facility Type, i.e 'Hospital, Clinic etc",
                max_length=250,
                on_delete=django.db.models.deletion.CASCADE,
                to="beneficiary.facilitytype",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="implementing_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Related Implementing Partner.",
                max_length=250,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="beneficiary.implementingpartner",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="province",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="beneficiary.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="service_provider",
            field=models.ManyToManyField(to="beneficiary.ServiceProvider"),
        ),
    ]
