# Generated by Django 3.1.13 on 2021-11-05 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0012_auto_20211105_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='junior_secondary_qualification',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='senior_secondary_qualification',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_id',
            field=models.UUIDField(default=uuid.UUID('bcbecbea-5a60-4211-bf65-ebfd7fe779d6'), editable=False),
        ),
    ]
