# Generated by Django 3.1.13 on 2021-11-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0009_auto_20211105_1231'),
        ('beneficiary', '0013_auto_20211105_1305'),
        ('beneficiary', '0010_auto_20211105_0727'),
    ]

    operations = [
    ]
