# Generated by Django 3.1.13 on 2021-11-05 16:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0014_merge_20211105_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='beneficiary_code',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='beneficiary_id',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='location',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='agent_ID',
            field=models.ForeignKey(default='5E6BBDF', on_delete=django.db.models.deletion.PROTECT, to='beneficiary.agentdetail'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_ID',
            field=models.UUIDField(default=uuid.UUID('eb3283b9-7ec0-4941-aa51-25a9c6620b7f'), editable=False),
        ),
        migrations.AlterField(
            model_name='agentdetail',
            name='agend_ID',
            field=models.CharField(default='0971CC0', max_length=100, verbose_name='Agent Id'),
        ),
        migrations.AlterField(
            model_name='agentdetail',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='education_level',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('primary', 'Primary'), ('basic', 'Basic'), ('secondary', "Secondary O'Level"), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('doctrate', 'Doctrate'), ('phd', 'PHD')], max_length=300, null=True, verbose_name='Education level'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name_of_spouse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of children'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='number_of_siblings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of siblings'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='Profile Photo'),
        ),
    ]
