# Generated by Django 3.1.13 on 2021-12-01 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary", "0017_auto_20211201_0954"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lab",
            old_name="date",
            new_name="requested_date",
        ),
        migrations.AddField(
            model_name="lab",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lab",
            name="results",
            field=models.TextField(blank=True, null=True, verbose_name="Lab Results"),
        ),
        migrations.AddField(
            model_name="lab",
            name="results_status",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Lab Results Status"
            ),
        ),
        migrations.CreateModel(
            name="BeneficiaryService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Extra Details/Comment"
                    ),
                ),
                ("interaction_date", models.DateTimeField(blank=True, null=True)),
                (
                    "no_of_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="No of Days"
                    ),
                ),
                (
                    "when_to_take",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="When to Take",
                    ),
                ),
                ("creeated", models.DateTimeField(blank=True, null=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beneficiary.beneficiary",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beneficiary.facility",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beneficiary.lab",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beneficiary.prescription",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beneficiary.service",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="beneficiary.serviceproviderpersonel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiary Service",
                "verbose_name_plural": "Beneficiary Services",
            },
        ),
    ]
