# Generated by Django 3.1.13 on 2021-12-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0020_auto_20211202_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='service',
            name='facility',
        ),
    ]
