# Generated by Django 3.1.13 on 2021-12-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary", "0022_beneficiary_facility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beneficiary",
            old_name="facility",
            new_name="service_facility",
        ),
        migrations.RemoveField(
            model_name="beneficiary",
            name="service_provider",
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="registered_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registerd_facility",
                to="beneficiary.facility",
            ),
        ),
    ]
