# Generated by Django 3.1.13 on 2021-12-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiary", "0023_auto_20211202_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="art_status",
            field=models.CharField(
                blank=True,
                choices=[("enrolled", "Enrolled"), ("not_enrolled", "Not Enrolled")],
                max_length=100,
                null=True,
                verbose_name="ART Status",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="hiv_status",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="HIV Status"
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="last_vl",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Last Viral Load"
            ),
        ),
    ]
