# Generated by Django 3.1.13 on 2021-12-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0024_auto_20211202_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True, verbose_name='HIV Status'),
        ),
    ]
