# Generated by Django 3.1.13 on 2021-12-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("beneficiary", "0024_auto_20211202_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdetail",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
            preserve_default=False,
        ),
    ]
