# Generated by Django 3.1.13 on 2021-12-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0026_auto_20211202_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='service_facility',
        ),
        migrations.RemoveField(
            model_name='serviceproviderpersonel',
            name='facility',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='service_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beneficiary.facility'),
        ),
    ]
