# Generated by Django 3.1.13 on 2021-12-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0027_auto_20211207_1502'),
        ('beneficiary', '0027_auto_20211210_0017'),
    ]

    operations = [
    ]
