# Generated by Django 3.1.13 on 2021-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0028_merge_20211210_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['-created'], 'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('unkown', 'Uknown')], max_length=100, null=True, verbose_name='HIV Status'),
        ),
    ]
