# Generated by Django 3.1.13 on 2021-12-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0029_auto_20211217_0940'),
        ('beneficiary', '0030_auto_20211215_1130'),
        ('beneficiary', '0030_auto_20211215_1136'),
    ]

    operations = [
    ]
