# Generated by Django 3.1.13 on 2021-12-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0031_merge_20211220_0030'),
        ('beneficiary', '0030_auto_20211215_1130'),
    ]

    operations = [
    ]
