# Generated by Django 3.1.13 on 2021-12-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0031_merge_20211218_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='document',
        ),
        migrations.RemoveField(
            model_name='service',
            name='document',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='documents',
            field=models.CharField(blank=True, editable=False, help_text='A jsonified object containing meta data where documents are stored.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='documents',
            field=models.CharField(blank=True, editable=False, help_text='A string representing a path to a directory where supporting documents are saved.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name_of_spouse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Spouse'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='lab',
            field=models.TextField(blank=True, null=True, verbose_name='Lab Comments'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription Comments'),
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
