# Generated by Django 3.1.13 on 2021-12-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0030_auto_20211215_1130'),
        ('beneficiary', '0032_auto_20211223_0615'),
    ]

    operations = [
    ]
