# Generated by Django 3.1.13 on 2021-12-24 13:10

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0033_merge_20211223_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='approved_by',
            field=models.CharField(default='Allen Chapman', help_text='Name of senior doctor or other official approving this medical record.', max_length=200, verbose_name='Approved by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='approver_signature',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='other'),
        ),
    ]
