# Generated by Django 3.1.13 on 2021-12-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0033_remove_medicalrecord_service_facility'),
        ('beneficiary', '0031_merge_20211223_1332'),
        ('beneficiary', '0036_medicalrecord_service_facility'),
    ]

    operations = [
    ]
