# Generated by Django 3.1.13 on 2021-12-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0031_merge_20211220_1350'),
        ('beneficiary', '0036_medicalrecord_service_facility'),
    ]

    operations = [
    ]
