# Generated by Django 3.1.13 on 2021-12-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0037_merge_20211228_1435'),
        ('beneficiary', '0037_merge_20211228_0814'),
    ]

    operations = [
    ]
