# Generated by Django 3.1.13 on 2021-12-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0038_medicalrecord_service_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiary.agent'),
        ),
    ]
