# Generated by Django 3.1.13 on 2021-12-31 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0039_auto_20211231_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdetail',
            name='beneficiary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiary.beneficiary'),
        ),
    ]
