# Generated by Django 3.1.13 on 2021-11-09 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_agentdetail_beneficiary_beneficiaryparent_servicearea_workdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetail',
            name='agend_ID',
            field=models.CharField(default='7EB1498', max_length=100, verbose_name='Agent Id'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='agent_ID',
            field=models.ForeignKey(default='14AE4C1', on_delete=django.db.models.deletion.PROTECT, to='beneficiary.agentdetail'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_ID',
            field=models.UUIDField(default=uuid.UUID('195d5ef8-3227-4831-9027-64501c2bc4ef'), editable=False),
        ),
    ]
