# Generated by Django 3.1.13 on 2021-11-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0005_auto_20211109_0849'),
        ('beneficiary', '0005_auto_20211107_2037'),
    ]

    operations = [
    ]
