# Generated by Django 3.1.13 on 2021-11-19 01:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0006_merge_20211119_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdetail',
            name='agend_ID',
            field=models.CharField(default='2D27D02', max_length=100, verbose_name='Agent Id'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='agent_ID',
            field=models.ForeignKey(default='60E9723', on_delete=django.db.models.deletion.PROTECT, to='beneficiary.agentdetail'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_ID',
            field=models.UUIDField(default=uuid.UUID('6c0b02be-0ce1-4be9-9781-31fcc2177226'), editable=False),
        ),
    ]
