# Generated by Django 3.1.13 on 2021-11-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0011_auto_20211124_1413'),
        ('beneficiary', '0007_auto_20211119_0100'),
    ]

    operations = [
    ]
